version: '3.8'

services:
  web:
    build: .
    command: gunicorn djangoCelery.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis

  celery:
    build: .
    command: celery -A djangoCelery worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A djangoCelery beat --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
