# Generated by Django 3.0.6 on 2020-08-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('first_number', models.IntegerField(default=0)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
    ]
